using Lumle.Core.Models;
using Lumle.Data.Data;
using Lumle.Data.Data.Abstracts;
using Lumle.Module.AdminConfig.Entities;
using System;

namespace Lumle.Module.AdminConfig.DbSeed
{
    public  class AdminConfigDataInitializer : IDataInitializer
    {
        public AdminConfigDataInitializer()
        {

        }
        public void Initialize(BaseContext _baseContext)
        {
            #region Seed Email Templates
            var emailTemplates = new EmailTemplate[]
            {
                new EmailTemplate {
                    Slug ="forgotpassword",
                    DefaultSlugDisplayName ="Forgot Password",
                    SlugDisplayName ="Forgot Password",
                    LastSlugDisplayName ="Forgot Password",
                    DefaultSubject ="Forgot Password",
                    Subject ="Forgot Password",
                    LastSubject ="Forgot Password",
                    DefaultBody = "<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This link has been generated in order to reset your password, please click the link within a day in order to reset your password.</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">Thank you!</p></div>",
                    Body ="<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This link has been generated in order to reset your password, please click the link within a day in order to reset your password.</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">Thank you!</p></div>",
                    LastBody="<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This link has been generated in order to reset your password, please click the link within a day in order to reset your password.</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px;\">Thank you!</p></div>",
                    CreatedDate=DateTime.UtcNow,
                    LastUpdated = DateTime.UtcNow
                },
                 new EmailTemplate {
                    Slug ="logincredential",
                    DefaultSlugDisplayName ="Login credential",
                    SlugDisplayName ="Login credential",
                    LastSlugDisplayName ="Login credential",
                    DefaultSubject ="Login credential",
                    Subject ="Login credential",
                    LastSubject ="Login credential",
                    DefaultBody = "<span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system.</span><div><span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></span><div><div><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system, your login details are:<br><span style=\"font-weight: bold;\">Role </span>: %role%&nbsp;<br><span style=\"font-weight: bold;\">Username </span>: %email%&nbsp;<br><span style=\"font-weight: bold;\">Password </span>: %password%&nbsp;<br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><span style=\"font-weight: bold;\">Url </span>: %loginurl%</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">If you think this link was send without your consent please contact admin of Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Thank you!</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Regards,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p></div><div><br></div></div></div>",
                    Body = "<span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system.</span><div><span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></span><div><div><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\" >< br ></ p >< p style = \"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system, your login details are:<br><span style=\"font-weight: bold;\">Role </span>: %role%&nbsp;<br><span style=\"font-weight: bold;\">Username </span>: %email%&nbsp;<br><span style=\"font - weight: bold; \">Password </span>: %password%&nbsp;<br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><span style=\"font-weight: bold;\">Url </span>: %loginurl%</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\" >< br ></ p >< p style = \"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">If you think this link was send without your consent please contact admin of Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Thank you!</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Regards,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p></div><div><br></div></div></div>",
                    LastBody ="<span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system.</span><div><span style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></span><div><div><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\" >< br ></ p >< p style = \"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">An account has been created in Lumle system, your login details are:<br><span style=\"font-weight: bold;\">Role </span>: %role%&nbsp;<br><span style=\"font-weight: bold;\">Username </span>: %email%&nbsp;<br><span style=\"font - weight: bold; \">Password </span>: %password%&nbsp;<br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><span style=\"font-weight: bold;\">Url </span>: %loginurl%</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\" >< br ></ p >< p style = \"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">If you think this link was send without your consent please contact admin of Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Thank you!</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; line-height: 1;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Regards,</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\">Lumle System</p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p><p style=\"color: rgb(0, 0, 0); font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;\"><br></p></div><div><br></div></div></div>",
                    CreatedDate=DateTime.UtcNow,
                    LastUpdated = DateTime.UtcNow
                },
                 new EmailTemplate {
                    Slug ="emailconfirmation",
                    DefaultSlugDisplayName ="Email Confirmation",
                    SlugDisplayName ="Email Confirmation",
                    LastSlugDisplayName ="Email Confirmation",
                    DefaultSubject ="Email Confirmation",
                    Subject ="Email Confirmation",
                    LastSubject ="Email Confirmation",
                    DefaultBody = "<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thanks for getting started with Lumle! We need a little more information to complete your registration, including confirmation of your email address. Click below to confirm your email address:</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thank you!</p></div>",
                    Body ="<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thanks for getting started with Lumle! We need a little more information to complete your registration, including confirmation of your email address. Click below to confirm your email address:</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thank you!</p></div>",
                    LastBody="<span style=\"background-color: transparent; color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">This mail is auto generated from Lumle.</span><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body mce-item - table\" style=\"border: 1px dashed rgb(187, 187, 187); color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><tbody></tbody></table><div><br></div><div><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Dear %username%,</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thanks for getting started with Lumle! We need a little more information to complete your registration, including confirmation of your email address. Click below to confirm your email address:</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">%url%</p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">If you think this link was send without your consent please contact admin of Lumle System!<br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \"><br></p><p style=\"color: rgb(0, 0, 0); font - family: Verdana, Arial, Helvetica, sans - serif; font - size: 11px; \">Thank you!</p></div>",
                    CreatedDate=DateTime.UtcNow,
                    LastUpdated = DateTime.UtcNow
                },
                new EmailTemplate {
                    Slug ="systemhealthreport",
                    DefaultSlugDisplayName ="System Health Report",
                    SlugDisplayName ="System Health Report",
                    LastSlugDisplayName ="System Health Report",
                    DefaultSubject ="System Health Report",
                    Subject ="System Health Report",
                    LastSubject ="System Health Report",
                    DefaultBody = "<div><span style=\"color: rgb(0, 0, 0);\">This mail is auto generated from Lumle.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Dear %username%,</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Following are the system health report of services conducted in the background of Lumle. Please go through it.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\"><table class=\"table table-bordered\"><tbody><tr><td><span style=\"font-weight: bold;\">Service Name</span><br></td><td><span style=\"font-weight: bold;\">Status</span><br></td></tr><tr><td>%serviceName1%<br></td><td>%serviceStatus1%<br></td></tr><tr><td>%serviceName2%<br></td><td>%serviceStatus2%<br></td></tr><tr><td>%serviceName3%<br></td><td>%serviceStatus3%</td></tr></tbody></table></span></div><div><br></div><div><span style=\"color: rgb(0, 0, 0);\">If you think this link was send without your consent please contact admin of Lumle System!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Thank you!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Ekbana Pte.Ltd,</span></div><div><span style=\"color: rgb(0, 0, 0);\">Jwagal, Lalitpur</span></div>",
                    Body ="<div><span style=\"color: rgb(0, 0, 0);\">This mail is auto generated from Lumle.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Dear %username%,</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Following are the system health report of services conducted in the background of Lumle. Please go through it.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\"><table class=\"table table-bordered\"><tbody><tr><td><span style=\"font-weight: bold;\">Service Name</span><br></td><td><span style=\"font-weight: bold;\">Status</span><br></td></tr><tr><td>%serviceName1%<br></td><td>%serviceStatus1%<br></td></tr><tr><td>%serviceName2%<br></td><td>%serviceStatus2%<br></td></tr><tr><td>%serviceName3%<br></td><td>%serviceStatus3%</td></tr></tbody></table></span></div><div><br></div><div><span style=\"color: rgb(0, 0, 0);\">If you think this link was send without your consent please contact admin of Lumle System!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Thank you!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Ekbana Pte.Ltd,</span></div><div><span style=\"color: rgb(0, 0, 0);\">Jwagal, Lalitpur</span></div>",
                    LastBody ="<div><span style=\"color: rgb(0, 0, 0);\">This mail is auto generated from Lumle.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Dear %username%,</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Following are the system health report of services conducted in the background of Lumle. Please go through it.</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\"><table class=\"table table-bordered\"><tbody><tr><td><span style=\"font-weight: bold;\">Service Name</span><br></td><td><span style=\"font-weight: bold;\">Status</span><br></td></tr><tr><td>%serviceName1%<br></td><td>%serviceStatus1%<br></td></tr><tr><td>%serviceName2%<br></td><td>%serviceStatus2%<br></td></tr><tr><td>%serviceName3%<br></td><td>%serviceStatus3%</td></tr></tbody></table></span></div><div><br></div><div><span style=\"color: rgb(0, 0, 0);\">If you think this link was send without your consent please contact admin of Lumle System!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Thank you!</span></div><div><span style=\"color: rgb(0, 0, 0);\"><br></span></div><div><span style=\"color: rgb(0, 0, 0);\">Ekbana Pte.Ltd,</span></div><div><span style=\"color: rgb(0, 0, 0);\">Jwagal, Lalitpur</span></div>",
                    CreatedDate =DateTime.UtcNow,
                    LastUpdated = DateTime.UtcNow
                }
            };

            _baseContext.Set<EmailTemplate>().AddRange(emailTemplates);
            _baseContext.SaveChanges();
            #endregion

            #region seed Credential Category
            var credentialCategories = new CredentialCategory[]
            {
                new CredentialCategory {Name="Email Service", CreatedDate=DateTime.UtcNow, LastUpdated= DateTime.UtcNow },
                new CredentialCategory {Name="General", CreatedDate=DateTime.UtcNow, LastUpdated= DateTime.UtcNow },
                new CredentialCategory {Name="Twillio SMS", CreatedDate=DateTime.UtcNow, LastUpdated= DateTime.UtcNow }
            };

            _baseContext.Set<CredentialCategory>().AddRange(credentialCategories);
            _baseContext.SaveChanges();
            #endregion

            #region seed Credential
            var credentials = new Credential[]
            {
                //Credential of Email Service Category
                new Credential {CredentialCategoryId=1, Slug="smtpmailserver", DisplayName="Mail server", Value="smtp.mailgun.org", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=1, Slug="smtpusername", DisplayName="Username", Value="postmaster@almostme.com", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=1, Slug="smtpadminemail", DisplayName="Admin email", Value="info@ekbana.com", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=1, Slug="smtpnoreplyemail", DisplayName="No reply email", Value="no-reply@ekbana.com", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=1, Slug="smtpuserpassword", DisplayName="Password", Value="4d4d6a192c66c2e4b042b290bba2768b", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },

                //Credential of General Category
                new Credential {CredentialCategoryId=2, Slug="loginurl", DisplayName="Application login page url", Value="", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=2, Slug="homeurl", DisplayName="Application home page url", Value="", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },

                //Credential for Twilio Sms Service
                new Credential {CredentialCategoryId=3, Slug="twiliobaseuri", DisplayName="Twilio sms end point", Value="https://api.twilio.com", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=3, Slug="twiliorequesturi", DisplayName="Twilio request uri", Value="2010-04-01/Accounts/{twilioaccountsid}/Messages.json", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=3, Slug="twilioaccountsid", DisplayName="Twilio account sid", Value="AC8b6923c25b5cec4884d3aaeb2f759ded", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=3, Slug="twilioauthtoken", DisplayName="Twilio auth token", Value="7f274ed65e3700074b8b92a90ce4df83", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow },
                new Credential {CredentialCategoryId=3, Slug="twiliofrom", DisplayName="Twilio phone number", Value="+15005550006", CreatedDate=DateTime.UtcNow, LastUpdated=DateTime.UtcNow }

            };

            _baseContext.Set<Credential>().AddRange(credentials);
            _baseContext.SaveChanges();
            #endregion

            #region AdminConfig System Setting
            var systemSetting = new AppSystem
            {
                Slug = "systemmaintenancemode",
                Status = "0",
                CreatedDate = DateTime.UtcNow,
                LastUpdated = DateTime.UtcNow,
                LastUpdatedBy = "Auto"
            };

            _baseContext.Set<AppSystem>().Add(systemSetting);
            _baseContext.SaveChanges();

            #endregion

        }
    }
}
